import type { BrowserTab, WorkspaceRecord } from "@/lib/types";
import { cleanDomain, formatTimestamp } from "@/lib/utils";

function tabLine(tab: BrowserTab): string {
  const domain = cleanDomain(tab.url);
  const label = tab.title || domain || tab.url;
  if (tab.url) return `- [${label}](${tab.url})${domain ? ` _(${domain})_` : ""}`;
  return `- ${label}`;
}

// Render a full workspace analysis to portable Markdown.
export function workspaceToMarkdown(record: WorkspaceRecord): string {
  const a = record.analysis;
  const lines: string[] = [];

  lines.push(`# ${record.title}`);
  lines.push("");
  if (record.goal) lines.push(`**Goal:** ${record.goal}`);
  if (record.timeRemaining) lines.push(`**Time remaining:** ${record.timeRemaining}`);
  lines.push(`**Created:** ${formatTimestamp(record.createdAt)}`);
  lines.push(`**Urgency:** ${a.urgencyLevel} · **Tabs analyzed:** ${a.totalTabs} · **Estimated focus:** ${a.estimatedFocusMinutes} min`);
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(`- **Main problem:** ${a.mainProblem}`);
  lines.push(`- **Focus recommendation:** ${a.focusRecommendation}`);
  lines.push(`- **First thing to do:** ${a.firstThingToDo}`);
  lines.push(`- **Risk warning:** ${a.riskWarning}`);
  lines.push("");

  // Grouped tabs
  lines.push("## Grouped Tabs");
  lines.push("");
  for (const group of a.groups) {
    lines.push(`### ${group.name} — ${group.action.toUpperCase()} · ${group.priority} priority`);
    lines.push("");
    if (group.explanation) {
      lines.push(`_${group.explanation}_`);
      lines.push("");
    }
    for (const tab of group.tabs) lines.push(tabLine(tab));
    lines.push("");
  }

  // Action plan
  lines.push("## Action Plan");
  lines.push("");
  a.nextTasks.forEach((task, i) => {
    lines.push(
      `${i + 1}. **${task.title}** — _${task.priority} priority, ~${task.estimatedMinutes} min_${task.completed ? " ✅" : ""}`,
    );
    if (task.whyItMatters) lines.push(`   - Why it matters: ${task.whyItMatters}`);
    for (const tab of task.relatedTabs) {
      lines.push(`   - ${cleanDomain(tab.url) || tab.title}`);
    }
  });
  lines.push("");

  // Panic mode
  if (a.panicMode) {
    lines.push("## Panic Mode");
    lines.push("");
    const sections: [string, string[]][] = [
      ["Do Now", a.panicMode.doNow],
      ["Cut", a.panicMode.cut],
      ["Ignore", a.panicMode.ignore],
      ["Final Sprint Plan", a.panicMode.finalSprintPlan],
      ["Minimum Viable Submission", a.panicMode.minimumViableSubmission],
    ];
    for (const [heading, items] of sections) {
      if (!items.length) continue;
      lines.push(`### ${heading}`);
      for (const item of items) lines.push(`- ${item}`);
      lines.push("");
    }
  }

  // Focus session
  lines.push("## Focus Session");
  lines.push("");
  a.focusSession.forEach((block) => {
    lines.push(`- **${block.label}** (${block.minutes} min): ${block.instructions}`);
  });
  lines.push("");

  // Distraction cleanup
  lines.push("## Distraction Cleanup");
  lines.push("");
  const cleanup: [string, BrowserTab[]][] = [
    ["Close now", a.distractionCleanup.closeNow],
    ["Save for later", a.distractionCleanup.saveForLater],
    ["Keep pinned", a.distractionCleanup.keepPinned],
  ];
  for (const [heading, tabs] of cleanup) {
    lines.push(`### ${heading}`);
    if (tabs.length === 0) lines.push("- _(none)_");
    for (const tab of tabs) lines.push(tabLine(tab));
    lines.push("");
  }

  lines.push("---");
  lines.push("_Generated by TabZero._");
  lines.push("");

  return lines.join("\n");
}
